Tinybit.RGB_Car_Big(Tinybit.enColor.Red)
music.playTone(196, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
music.playTone(196, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
music.playTone(262, music.beat(BeatFraction.Whole))
Tinybit.RGB_Car_Big(Tinybit.enColor.White)
music.playTone(262, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
music.playTone(294, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
music.playTone(262, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Yellow)
music.playTone(247, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Red)
music.playTone(220, music.beat(BeatFraction.Whole))
Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
music.playTone(220, music.beat(BeatFraction.Whole))
Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
music.rest(music.beat(BeatFraction.Whole))
music.playTone(220, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.White)
music.playTone(220, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
music.playTone(294, music.beat(BeatFraction.Whole))
Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
music.playTone(294, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Yellow)
music.playTone(330, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Red)
music.playTone(294, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
music.playTone(262, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
music.playTone(247, music.beat(BeatFraction.Whole))
Tinybit.RGB_Car_Big(Tinybit.enColor.White)
music.playTone(196, music.beat(BeatFraction.Whole))
Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
music.rest(music.beat(BeatFraction.Whole))
music.playTone(196, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
music.playTone(196, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Red)
music.playTone(330, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
music.playTone(349, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
music.playTone(330, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.White)
music.playTone(294, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
music.playTone(262, music.beat(BeatFraction.Whole))
Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
music.playTone(220, music.beat(BeatFraction.Whole))
Tinybit.RGB_Car_Big(Tinybit.enColor.Yellow)
music.rest(music.beat(BeatFraction.Whole))
music.playTone(196, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Red)
music.playTone(196, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
music.playTone(220, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
music.playTone(294, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.White)
music.playTone(247, music.beat(BeatFraction.Half))
Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
music.playTone(262, music.beat(BeatFraction.Whole))
Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
basic.pause(2000)
